"""Tests for :mod:`animedex.config.buildmeta`.

The build_info module is generated by ``tools/generate_build_info.py`` and
.gitignore'd, so the loader must work in both states - present and absent.
This test exercises the always-true path (loader produces a dict), the
absent fallback (no build_info.py), and a synthetic present-state path
(monkey-patched module) so we never need to mutate the real workspace.
"""

import sys
import types

import pytest

from animedex.config import buildmeta


@pytest.mark.unittest
class TestLoaderShape:
    def test_build_info_dict_has_required_keys(self):
        info = buildmeta.get_build_info()
        for key in (
            "available",
            "commit",
            "commit_short",
            "describe",
            "tag",
            "dirty",
            "build_time",
            "build_host",
        ):
            assert key in info, f"BUILD_INFO is missing key {key!r}: {info}"

    def test_get_build_info_returns_copy(self):
        a = buildmeta.get_build_info()
        b = buildmeta.get_build_info()
        a["commit"] = "mutated"
        assert b["commit"] != "mutated", "get_build_info() must return a copy"


@pytest.mark.unittest
class TestFormatHelpers:
    def test_format_short_when_unavailable(self):
        # Force the absent state regardless of the actual workspace.
        original = dict(buildmeta.BUILD_INFO)
        try:
            buildmeta.BUILD_INFO.update({"available": False})
            line = buildmeta.format_short()
            assert "build info not generated" in line
        finally:
            buildmeta.BUILD_INFO.clear()
            buildmeta.BUILD_INFO.update(original)

    def test_format_short_when_available(self):
        original = dict(buildmeta.BUILD_INFO)
        try:
            buildmeta.BUILD_INFO.update(
                {
                    "available": True,
                    "commit_short": "abc1234",
                    "tag": "v0.0.1",
                    "dirty": False,
                    "build_time": "2026-05-07T03:35:00Z",
                }
            )
            line = buildmeta.format_short()
            assert "abc1234" in line
            assert "tag v0.0.1" in line
            assert "clean" in line
            assert "built 2026-05-07T03:35:00Z" in line
            assert "dirty" not in line
        finally:
            buildmeta.BUILD_INFO.clear()
            buildmeta.BUILD_INFO.update(original)

    def test_format_short_dirty(self):
        original = dict(buildmeta.BUILD_INFO)
        try:
            buildmeta.BUILD_INFO.update(
                {
                    "available": True,
                    "commit_short": "deadbef",
                    "tag": None,
                    "dirty": True,
                    "build_time": "2026-05-07T03:35:00Z",
                }
            )
            line = buildmeta.format_short()
            assert "deadbef" in line
            assert "dirty" in line
            assert "tag " not in line
        finally:
            buildmeta.BUILD_INFO.clear()
            buildmeta.BUILD_INFO.update(original)

    def test_format_block_when_unavailable(self):
        original = dict(buildmeta.BUILD_INFO)
        try:
            buildmeta.BUILD_INFO.update({"available": False})
            block = buildmeta.format_block()
            assert "(not generated)" in block
            assert "make build_info" in block
        finally:
            buildmeta.BUILD_INFO.clear()
            buildmeta.BUILD_INFO.update(original)

    def test_format_block_when_available(self):
        original = dict(buildmeta.BUILD_INFO)
        try:
            buildmeta.BUILD_INFO.update(
                {
                    "available": True,
                    "commit": "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
                    "commit_short": "deadbef",
                    "describe": "v0.0.1-3-gdeadbef",
                    "tag": None,
                    "dirty": True,
                    "build_time": "2026-05-07T03:35:00Z",
                    "build_host": "ci-runner",
                }
            )
            block = buildmeta.format_block()
            assert "deadbef" in block
            assert "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef" in block
            assert "v0.0.1-3-gdeadbef" in block
            assert "<none>" in block  # tag is None
            assert "True" in block  # dirty
            assert "ci-runner" in block
        finally:
            buildmeta.BUILD_INFO.clear()
            buildmeta.BUILD_INFO.update(original)


@pytest.mark.unittest
class TestLoaderAbsent:
    def test_load_returns_unavailable_when_module_missing(self, monkeypatch):
        # ``from animedex.config import build_info`` first looks up the
        # attribute on animedex.config, then falls back to a real import.
        # If a previous test or the actual build has cached the module
        # under that attribute, patching sys.modules alone is not enough;
        # we also have to drop the attribute so the from-import re-resolves.
        import animedex.config

        monkeypatch.setitem(sys.modules, "animedex.config.build_info", None)
        monkeypatch.delattr(animedex.config, "build_info", raising=False)

        info = buildmeta._load()
        assert info["available"] is False
        assert info["commit"] == "unknown"
        assert info["commit_short"] == "unknown"
        assert info["describe"] == "unknown"
        assert info["tag"] is None
        assert info["dirty"] is False
        assert info["build_time"] == "unknown"


@pytest.mark.unittest
class TestLoaderPresent:
    def test_load_picks_up_synthetic_module(self, monkeypatch):
        import animedex.config

        synthetic = types.ModuleType("animedex.config.build_info")
        synthetic.__COMMIT__ = "f" * 40
        synthetic.__COMMIT_SHORT__ = "fffffff"
        synthetic.__GIT_DESCRIBE__ = "v0.0.1-1-gfffffff-dirty"
        synthetic.__TAG__ = "v0.0.1"
        synthetic.__DIRTY__ = True
        synthetic.__BUILD_TIME__ = "2026-05-07T00:00:00Z"
        synthetic.__BUILD_HOST__ = "synthetic"

        monkeypatch.setitem(sys.modules, "animedex.config.build_info", synthetic)
        monkeypatch.setattr(animedex.config, "build_info", synthetic, raising=False)

        info = buildmeta._load()
        assert info["available"] is True
        assert info["commit_short"] == "fffffff"
        assert info["dirty"] is True
        assert info["tag"] == "v0.0.1"
        assert info["build_host"] == "synthetic"
