"""Configuration and metadata sub-package for animedex.

Holds:

* :mod:`animedex.config.meta` - committed project identity (title, version,
  author, etc.). Always present.
* :mod:`animedex.config.buildmeta` - committed loader for the optional
  per-build metadata. Always present; reports ``available=False`` when
  the underlying ``build_info.py`` has not been generated.
* :mod:`animedex.config.build_info` (uncommitted, ``.gitignore``'d) -
  generated by ``tools/generate_build_info.py`` and consumed by the
  loader above.
"""

from . import buildmeta, meta

__all__ = ["meta", "buildmeta"]
