"""Configuration and metadata sub-package for animedex.

Holds:

* :mod:`animedex.config.profile` - the public
  :class:`~animedex.config.profile.Config` object, programmatic
  equivalent of the CLI flag stack (re-exported here as
  ``from animedex.config import Config`` per plan 05 §4).
* :mod:`animedex.config.meta` - committed project identity (title,
  version, author, etc.). Always present.
* :mod:`animedex.config.buildmeta` - committed loader for the optional
  per-build metadata. Always present; reports ``available=False`` when
  the underlying ``build_info.py`` has not been generated.
* :mod:`animedex.config.build_info` (uncommitted, ``.gitignore``'d) -
  generated by ``tools/generate_build_info.py`` and consumed by the
  loader above.

Submodules other than ``profile`` are not re-exported: import them
explicitly (``import animedex.config.meta`` / ``import
animedex.config.buildmeta``) to avoid duplicate Sphinx object
descriptions.
"""

from animedex.config.profile import Config


__all__ = ["Config"]
