"""
Generate the PyInstaller spec file used to package animedex.

Mirrors the pattern from ``pyfcstm/tools/generate_spec.py`` on the
``dev/damnx`` branch: produce a deterministic ``.spec`` file under
version-controlled rules, rather than passing increasingly elaborate
flags to ``pyinstaller`` on the command line. The spec captures:

* The Python entry point (``animedex_cli.py``).
* The data files collected by :mod:`tools.resources`.
* The hidden imports that PyInstaller's static scanner cannot reach,
  most notably ``animedex.config.build_info`` (loaded via try/except
  so that animedex still works when the file has not been generated).
* An aggressive *exclude* list that drops the data-science, GUI, and
  test/packaging stacks Python pulls in by default but which animedex
  does not need at runtime; this keeps the binary small and the
  startup cost low.

There is **no logo / icon** asset in this build: the project ships
text only.

Usage::

    python tools/generate_spec.py -o animedex.spec
    pyinstaller animedex.spec --noconfirm --clean
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

#: Modules that the binary should never bundle. Each entry is a top-level
#: import path; PyInstaller's exclude semantics treat them as prefixes
#: only when stated as such, so a literal name like ``"numpy"`` will
#: still exclude ``numpy.linalg`` and friends.
EXCLUDED_MODULES = [
    # GUI toolkits
    "tkinter",
    # Data-science and notebook stacks animedex does not depend on.
    "matplotlib",
    "numpy",
    "pandas",
    "scipy",
    "IPython",
    "jupyter",
    "notebook",
    # Test, doc, and packaging tooling that should never ship.
    "pytest",
    "unittest",
    "doctest",
    "pydoc",
    "_pytest",
    "py",
    "PyInstaller",
    "_pyinstaller_hooks_contrib",
    "altgraph",
    "macholib",
    "pefile",
    "win32ctypes",
    "distutils",
    "setuptools",
    "pip",
    # Misc stdlib helpers and HTTP servers that animedex never starts.
    "xmlrpc",
    "http.server",
]

#: Modules PyInstaller's static analyser does not reach unaided. The
#: ``animedex.config.build_info`` module is the single per-build artifact
#: from ``tools/generate_build_info.py`` and is loaded via try/except in
#: :mod:`animedex.config.buildmeta`, so we list it explicitly so the
#: bundle includes it whenever it has been generated. (When it has
#: *not* been generated, PyInstaller will skip it silently because the
#: file does not exist; the loader in buildmeta degrades gracefully.)
HIDDEN_IMPORTS = [
    "animedex.config.build_info",
]


def collect_datas() -> list:
    """Resolve the data-file list for ``Analysis.datas``.

    Calls :func:`tools.resources.get_resource_files` and converts to the
    plain Python list PyInstaller expects. Errors are logged and
    swallowed so a missing ``tools.resources`` does not break the
    binary build.

    :return: List of ``(src_path, dst_dir)`` tuples.
    :rtype: list
    """
    datas = []
    try:
        from tools.resources import get_resource_files

        for src_file, dst_dir in get_resource_files():
            datas.append((src_file, dst_dir))
    except Exception as exc:  # pragma: no cover - defensive logging
        print(f"Warning: tools.resources failed: {exc}", file=sys.stderr)
    return datas


_SPEC_TEMPLATE = """# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by tools/generate_spec.py. DO NOT EDIT BY HAND;
# any change here will be overwritten on the next `make build`.

a = Analysis(
    ['animedex_cli.py'],
    pathex=[],
    binaries=[],
    datas={datas!r},
    hiddenimports={hidden!r},
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes={excludes!r},
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='animedex',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
"""


def generate_spec() -> tuple:
    """Render the spec text and return ``(content, data_count)``.

    :return: A tuple of the spec body and the number of data files that
             :func:`collect_datas` produced; the latter is printed for
             situational awareness when running the script.
    :rtype: tuple
    """
    datas = collect_datas()
    content = _SPEC_TEMPLATE.format(
        datas=datas,
        hidden=HIDDEN_IMPORTS,
        excludes=EXCLUDED_MODULES,
    )
    return content, len(datas)


def main() -> int:
    """Argparse entry point for ``python -m tools.generate_spec``.

    :return: Process exit code.
    :rtype: int
    """
    parser = argparse.ArgumentParser(description="Generate the animedex PyInstaller spec.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("animedex.spec"),
        help="Output spec path (default: animedex.spec).",
    )
    args = parser.parse_args()

    content, data_count = generate_spec()
    args.output.write_text(content, encoding="utf-8")
    print(
        f"Generated {args.output} "
        f"(datas={data_count}, hidden={len(HIDDEN_IMPORTS)}, "
        f"excludes={len(EXCLUDED_MODULES)})"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
